### ISSUE TITLE
Elude not compiling for VS2013

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#106]
Compiling elude on native Windows with VS2013 results in the following warnings and errors:
```
"C:\vagrant\build\elude\PACKAGE.vcxproj" (default target) (1) ->
"C:\vagrant\build\elude\ALL_BUILD.vcxproj" (default target) (2) ->
"C:\vagrant\build\elude\elude.vcxproj" (default target) (4) ->
"C:\vagrant\build\elude\eludelibrary.vcxproj" (default target) (5) ->
(ClCompile target) -> 
  C:\vagrant\src\percolator\src\elude_tool\RetentionModel.cpp(61): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(48): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(84): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(142): warning C4244: 'argument' : conversion from 'time_t' to 'unsigned int', possible loss of data [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(168): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(177): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(209): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\LTSRegression.cpp(220): warning C4018: '<' : signed/unsigned mismatch [C:\vagrant\build\elude\eludelibrary.vcxproj]
  c:\vagrant\src\percolator\src\elude_tool\libsvrmodel.cpp(281): warning C4715: 'LibSVRModel::LoadModel' : not all control paths return a value [C:\vagrant\build\elude\eludelibrary.vcxproj]


"C:\vagrant\build\elude\PACKAGE.vcxproj" (default target) (1) ->
"C:\vagrant\build\elude\ALL_BUILD.vcxproj" (default target) (2) ->
"C:\vagrant\build\elude\elude.vcxproj" (default target) (4) ->
"C:\vagrant\build\elude\eludelibrary.vcxproj" (default target) (5) ->
(ClCompile target) -> 
  C:\vagrant\src\percolator\src\elude_tool\RetentionModel.cpp(80): error C2057: expected constant expression [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\RetentionModel.cpp(80): error C2466: cannot allocate an array of constant size 0 [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\RetentionModel.cpp(80): error C2087: 'temp' : missing subscript [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\RetentionModel.cpp(80): error C2133: 'temp' : unknown size [C:\vagrant\build\elude\eludelibrary.vcxproj]
  C:\vagrant\src\percolator\src\elude_tool\EludeCaller.cpp(23): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory [C:\vagrant\build\elude\eludelibrary.vcxproj]
  c:\vagrant\src\percolator\src\elude_tool\libsvrmodel.cpp(124): error C4716: 'LibSVRModel::TrainModel' : must return a value [C:\vagrant\build\elude\eludelibrary.vcxproj]
  c:\vagrant\src\percolator\src\elude_tool\libsvrmodel.cpp(85): error C4716: 'LibSVRModel::InitSVRParameters' : must return a value [C:\vagrant\build\elude\eludelibrary.vcxproj]
  c:\vagrant\src\percolator\src\elude_tool\libsvrmodel.cpp(260): error C4716: 'LibSVRModel::SaveModel' : must return a value [C:\vagrant\build\elude\eludelibrary.vcxproj]

    9 Warning(s)
    8 Error(s)
```

The missing `dirent.h` error seems to be the only real problem (the first 4 can be fixed by changing a 2D array to a 2D vector and the last 3 can just return a `0`). `dirent.h` is not available in VS, but could be downloaded and compiled separately.
